import Head from 'next/head'
import About from '../components/About'
import AboutEyantra from '../components/AboutEyantra'
import ApplyNow from '../components/ApplyNow'
import LandingPage from '../components/LandingPage'
import Shedule from '../components/Shedule'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Arduino Development and Programing Workshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <main  className={styles.container}>
        <LandingPage/>
      </main>
      <About />
      <ApplyNow />
      <Shedule />
      <AboutEyantra />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p style={{textAlign : "center"}}>Created and Designed by <br/>Tanmay Singewar</p>
        </a>
      </footer>
    </div>
  )
}
